[functions]
  directory = "netlify/functions"  # 함수가 위치한 디렉토리

[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[[redirects]]
  from = "/u/*"
  to = "/index.html"
  status = 200
